// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Data;

#nullable disable

namespace SegundaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260311091642_RenombreTextoObservaciones")]
    partial class RenombreTextoObservaciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegundaAPI.Models.Articulos", b =>
                {
                    b.Property<string>("IdArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<string>("CCCompra")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCCompra");

                    b.Property<string>("CCVenta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCVenta");

                    b.Property<string>("DescArticulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Estado");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Familia");

                    b.Property<decimal>("PesoBruto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("PesoBruto");

                    b.Property<decimal>("PesoNeto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("PesoNeto");

                    b.Property<decimal>("Plazo")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Plazo");

                    b.Property<string>("TipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIva");

                    b.Property<string>("UdCompra")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UdCompra");

                    b.Property<string>("UdVenta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UdVenta");

                    b.Property<decimal>("Volumen")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Volumen");

                    b.HasKey("IdArticulo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SegundaAPI.Models.Clientes", b =>
                {
                    b.Property<string>("IdCliente")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDCliente");

                    b.Property<string>("CcCliente")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCCliente");

                    b.Property<string>("CifCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CifCliente");

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CodPostal");

                    b.Property<string>("DescCliente")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescCliente");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<decimal>("DtoComercial")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoComercial");

                    b.Property<string>("EMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Fax")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Fax");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("Movil")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Movil");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pais");

                    b.Property<string>("Poblacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Poblacion");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono2");

                    b.Property<string>("Web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraCabecera", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("BaseImponible");

                    b.Property<string>("CifProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CifProveedor");

                    b.Property<decimal>("DtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoFactura");

                    b.Property<decimal>("DtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFactura");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVencimiento");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("IdProveedor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDProveedor");

                    b.Property<decimal>("ImpDpp")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDpp");

                    b.Property<decimal>("ImpDtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDtoFactura");

                    b.Property<decimal>("ImpIva")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpIva");

                    b.Property<decimal>("ImpLineas")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpLineas");

                    b.Property<decimal>("ImpRE")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRE");

                    b.Property<decimal>("ImpRecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRecFinan");

                    b.Property<decimal>("ImpRetencion")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRetencion");

                    b.Property<decimal>("ImpTotal")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpTotal");

                    b.Property<string>("NFactura")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NFactura");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<decimal>("RecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RecFinan");

                    b.Property<decimal>("RetencionIRPF")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RetencionIRPF");

                    b.HasKey("IdFactura");

                    b.ToTable("FacturaCompraCabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraLinea", b =>
                {
                    b.Property<int>("IdLineaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLineaFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLineaFactura"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Cantidad");

                    b.Property<string>("DescArticulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<decimal>("Dto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Dto");

                    b.Property<decimal>("DtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("IDFactura")
                        .HasColumnType("int");

                    b.Property<string>("IdArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    b.Property<string>("IdUdMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDUdMedida");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Importe");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lote");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Precio");

                    b.Property<string>("TipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIVA");

                    b.HasKey("IdLineaFactura");

                    b.HasIndex("IdFactura");

                    b.ToTable("FacturaCompraLinea", t =>
                        {
                            t.Property("IDFactura")
                                .HasColumnName("IDFactura1");
                        });
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaCabecera", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("BaseImponible");

                    b.Property<string>("CifCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CifCliente");

                    b.Property<decimal>("DtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoFactura");

                    b.Property<decimal>("DtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("Estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("FechaFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFactura");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVencimiento");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("IdCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDCliente");

                    b.Property<decimal>("ImpDpp")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDpp");

                    b.Property<decimal>("ImpDtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDtoFactura");

                    b.Property<decimal>("ImpIva")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpIva");

                    b.Property<decimal>("ImpLineas")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpLineas");

                    b.Property<decimal>("ImpRE")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRE");

                    b.Property<decimal>("ImpRecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRecFinan");

                    b.Property<decimal>("ImpRetencion")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRetencion");

                    b.Property<decimal>("ImpTotal")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpTotal");

                    b.Property<string>("NFactura")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NFactura");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<decimal>("RecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RecFinan");

                    b.Property<decimal>("RetencionIRPF")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RetencionIRPF");

                    b.HasKey("IdFactura");

                    b.ToTable("FacturaVentaCabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaLinea", b =>
                {
                    b.Property<int>("IdLineaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLineaFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLineaFactura"));

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Cantidad");

                    b.Property<string>("DescArticulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<decimal>("Dto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Dto");

                    b.Property<decimal>("DtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("IDFactura")
                        .HasColumnType("int");

                    b.Property<string>("IdArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    b.Property<string>("IdUdMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDUdMedida");

                    b.Property<decimal>("Importe")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Importe");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lote");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<decimal>("Precio")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Precio");

                    b.Property<string>("TipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIVA");

                    b.HasKey("IdLineaFactura");

                    b.HasIndex("IdFactura");

                    b.ToTable("FacturaVentaLinea", t =>
                        {
                            t.Property("IDFactura")
                                .HasColumnName("IDFactura1");
                        });
                });

            modelBuilder.Entity("SegundaAPI.Models.Proveedores", b =>
                {
                    b.Property<string>("IdProveedor")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDProveedor");

                    b.Property<string>("CcProveedor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCProveedor");

                    b.Property<string>("CifProveedor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CifProveedor");

                    b.Property<string>("CodPostal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CodPostal");

                    b.Property<string>("DescProveedor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescProveedor");

                    b.Property<string>("Direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<decimal>("DtoComercial")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoComercial");

                    b.Property<string>("EMail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Fax")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Fax");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("Movil")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Movil");

                    b.Property<string>("Observaciones")
                        .HasColumnType("ntext")
                        .HasColumnName("Observaciones");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pais");

                    b.Property<string>("Poblacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Poblacion");

                    b.Property<string>("Provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono");

                    b.Property<string>("Telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono2");

                    b.Property<string>("Web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraLinea", b =>
                {
                    b.HasOne("SegundaAPI.Models.FacturaCompraCabecera", "Cabecera")
                        .WithMany("Lineas")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaLinea", b =>
                {
                    b.HasOne("SegundaAPI.Models.FacturaVentaCabecera", "Cabecera")
                        .WithMany("Lineas")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraCabecera", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaCabecera", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
