// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.Data;

#nullable disable

namespace SegundaAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227110816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegundaAPI.Models.Articulos", b =>
                {
                    b.Property<string>("idArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<string>("ccCompra")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCCompra");

                    b.Property<string>("ccVenta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCVenta");

                    b.Property<string>("descArticulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Estado");

                    b.Property<string>("familia")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Familia");

                    b.Property<decimal>("pesoBruto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("PesoBruto");

                    b.Property<decimal>("pesoNeto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("PesoNeto");

                    b.Property<decimal>("plazo")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Plazo");

                    b.Property<string>("tipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIva");

                    b.Property<string>("udCompra")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UdCompra");

                    b.Property<string>("udVenta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("UdVenta");

                    b.Property<decimal>("volumen")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Volumen");

                    b.HasKey("idArticulo");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("SegundaAPI.Models.Clientes", b =>
                {
                    b.Property<string>("IdCliente")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDCliente");

                    b.Property<string>("DescCliente")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescCliente");

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<string>("ccCliente")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCCliente");

                    b.Property<string>("cifCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CifCliente");

                    b.Property<string>("codPostal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CodPostal");

                    b.Property<string>("direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<decimal>("dtoComercial")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoComercial");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("fax")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Fax");

                    b.Property<string>("formaPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("movil")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Movil");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pais");

                    b.Property<string>("poblacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Poblacion");

                    b.Property<string>("provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("razonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono");

                    b.Property<string>("telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono2");

                    b.Property<string>("web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraCabecera", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFactura"));

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<decimal>("baseImponible")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("BaseImponible");

                    b.Property<string>("cifProveedor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CifProveedor");

                    b.Property<decimal>("dtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoFactura");

                    b.Property<decimal>("dtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("fechaFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFactura");

                    b.Property<DateTime?>("fechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVencimiento");

                    b.Property<string>("formaPago")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("idProveedor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDProveedor");

                    b.Property<decimal>("impDpp")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDpp");

                    b.Property<decimal>("impDtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDtoFactura");

                    b.Property<decimal>("impIva")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpIva");

                    b.Property<decimal>("impLineas")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpLineas");

                    b.Property<decimal>("impRE")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRE");

                    b.Property<decimal>("impRecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRecFinan");

                    b.Property<decimal>("impRetencion")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRetencion");

                    b.Property<decimal>("impTotal")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpTotal");

                    b.Property<string>("nFactura")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NFactura");

                    b.Property<string>("razonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<decimal>("recFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RecFinan");

                    b.Property<decimal>("retencionIRPF")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RetencionIRPF");

                    b.HasKey("idFactura");

                    b.ToTable("FacturaCompraCabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraLinea", b =>
                {
                    b.Property<int>("idLineaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLineaFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLineaFactura"));

                    b.Property<int>("IDFactura")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Cantidad");

                    b.Property<string>("descArticulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<decimal>("dto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Dto");

                    b.Property<decimal>("dtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<string>("idArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<int>("idFactura")
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    b.Property<string>("idUdMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDUdMedida");

                    b.Property<decimal>("importe")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Importe");

                    b.Property<string>("lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lote");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Precio");

                    b.Property<string>("tipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIVA");

                    b.HasKey("idLineaFactura");

                    b.HasIndex("idFactura");

                    b.ToTable("FacturaCompraLinea", t =>
                        {
                            t.Property("IDFactura")
                                .HasColumnName("IDFactura1");
                        });
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaCabecera", b =>
                {
                    b.Property<int>("idFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFactura"));

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<decimal>("baseImponible")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("BaseImponible");

                    b.Property<string>("cifCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CifCliente");

                    b.Property<decimal>("dtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoFactura");

                    b.Property<decimal>("dtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<int>("estado")
                        .HasColumnType("int")
                        .HasColumnName("Estado");

                    b.Property<DateTime?>("fechaFactura")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFactura");

                    b.Property<DateTime?>("fechaVencimiento")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaVencimiento");

                    b.Property<string>("formaPago")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("idCliente")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDCliente");

                    b.Property<decimal>("impDpp")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDpp");

                    b.Property<decimal>("impDtoFactura")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpDtoFactura");

                    b.Property<decimal>("impIva")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpIva");

                    b.Property<decimal>("impLineas")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpLineas");

                    b.Property<decimal>("impRE")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRE");

                    b.Property<decimal>("impRecFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRecFinan");

                    b.Property<decimal>("impRetencion")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpRetencion");

                    b.Property<decimal>("impTotal")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("ImpTotal");

                    b.Property<string>("nFactura")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("NFactura");

                    b.Property<string>("razonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<decimal>("recFinan")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RecFinan");

                    b.Property<decimal>("retencionIRPF")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("RetencionIRPF");

                    b.HasKey("idFactura");

                    b.ToTable("FacturaVentaCabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaLinea", b =>
                {
                    b.Property<int>("idLineaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDLineaFactura");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idLineaFactura"));

                    b.Property<int>("IDFactura")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<decimal>("cantidad")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Cantidad");

                    b.Property<string>("descArticulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescArticulo");

                    b.Property<decimal>("dto")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Dto");

                    b.Property<decimal>("dtoProntoPago")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoProntoPago");

                    b.Property<string>("idArticulo")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDArticulo");

                    b.Property<int>("idFactura")
                        .HasColumnType("int")
                        .HasColumnName("IDFactura");

                    b.Property<string>("idUdMedida")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDUdMedida");

                    b.Property<decimal>("importe")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Importe");

                    b.Property<string>("lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Lote");

                    b.Property<decimal>("precio")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("Precio");

                    b.Property<string>("tipoIva")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TipoIVA");

                    b.HasKey("idLineaFactura");

                    b.HasIndex("idFactura");

                    b.ToTable("FacturaVentaLinea", t =>
                        {
                            t.Property("IDFactura")
                                .HasColumnName("IDFactura1");
                        });
                });

            modelBuilder.Entity("SegundaAPI.Models.Proveedores", b =>
                {
                    b.Property<string>("IdProveedor")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("IDProveedor");

                    b.Property<string>("DescProveedor")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("DescProveedor");

                    b.Property<string>("Texto")
                        .HasColumnType("ntext")
                        .HasColumnName("Texto");

                    b.Property<string>("ccProveedor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("CCProveedor");

                    b.Property<string>("cifProveedor")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CifProveedor");

                    b.Property<string>("codPostal")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("CodPostal");

                    b.Property<string>("direccion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direccion");

                    b.Property<decimal>("dtoComercial")
                        .HasColumnType("numeric(23,8)")
                        .HasColumnName("DtoComercial");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("fax")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Fax");

                    b.Property<string>("formaPago")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("FormaPago");

                    b.Property<string>("movil")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Movil");

                    b.Property<string>("pais")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pais");

                    b.Property<string>("poblacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Poblacion");

                    b.Property<string>("provincia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Provincia");

                    b.Property<string>("razonSocial")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("RazonSocial");

                    b.Property<string>("telefono")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono");

                    b.Property<string>("telefono2")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("Telefono2");

                    b.Property<string>("web")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Web");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraLinea", b =>
                {
                    b.HasOne("SegundaAPI.Models.FacturaCompraCabecera", "Cabecera")
                        .WithMany("Lineas")
                        .HasForeignKey("idFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaLinea", b =>
                {
                    b.HasOne("SegundaAPI.Models.FacturaVentaCabecera", "Cabecera")
                        .WithMany("Lineas")
                        .HasForeignKey("idFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cabecera");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaCompraCabecera", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("SegundaAPI.Models.FacturaVentaCabecera", b =>
                {
                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
